spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 31150616
    url: jdbc:postgresql://localhost:5432/fs
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
